:rocket: ste up variables

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -14,47 +14,54 @@ jobs:
     steps:
       - name: Checkout the repository
         uses: actions/checkout@v4
-        with: 
+        with:
           ref: rescue-team-features
-        
+
       - name: Build the project
-        run: docker compose up -d
-        
+        env:
+           POSTGRES_USER: ${{secrets.POSTGRES_USER}}
+           POSTGRES_PASSWORD: ${{secret.POSTGRES_PASSWORD}}
+           POSTGRES_DB: ${{secret.POSTGRES_DB}}
+        run:
+          docker compose up -d
+
+
       - name: Wait for build
         run: |
-              docker compose logs 
-              curl -v http://localhost:4200 || echo "Failed to access frontend"
-            
-      #   run: |
-      #                retries=10
-      #                while [ $retries -gt 0 ]; do
-      #                if curl -s http://localhost:4200 > /dev/null; then
-      #                break
-      #                else
-      #                sleep 15
-      #                retries=$((retries - 1))
-      #                fi
-      #                done
-         
+          docker compose logs 
+          curl -v http://localhost:4200 || echo "Failed to access frontend"
           
+          #   run: |
+          #                retries=10
+          #                while [ $retries -gt 0 ]; do
+          #                if curl -s http://localhost:4200 > /dev/null; then
+          #                break
+          #                else
+          #                sleep 15
+          #                retries=$((retries - 1))
+          #                fi
+          #                done
+
+
       - name: Checkout the test repository
         uses: actions/checkout@v4
         with:
           repository: FoldiKrizsanIldiko/adoptAPet
           token: ${{secrets.FKI_ADOPTAPET}}
           ref: fki-Frontend-tests
-          
+
       - name: Set up JDK 21
         uses: actions/setup-java@v4
         with:
           java-version: '21'
           distribution: 'temurin'
           cache: maven
-          
+
       - name: Run tests CI tests
         run: |
           cd FontendTests/adoptAPetFrontend
           mvn test -Dcucumber.filter.tags="@workflow"
-          
+
       - name: Tear down services
         run: docker-compose down
+   
