:rocket: :bug: still cant find frontend

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -22,18 +22,9 @@ jobs:
         
       - name: Wait for build
         run: |
-            retries=10
-            while [ $retries -gt 0 ]; do
-              response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:4200)
-              if [ "$response" -eq 200 ]; then
-                echo "Frontend is ready!"
-                break
-              else
-                echo "Waiting for frontend... Response code: $response"
-                sleep 10
-                retries=$((retries - 1))
-              fi
-            done
+              docker compose logs frontend
+              curl -v http://frontend:80 || echo "Failed to access frontend"
+            
       #   run: |
       #                retries=10
       #                while [ $retries -gt 0 ]; do
